### ISSUE TITLE
Azure Debian 12 fetch: Error: Machine appears to have no Internet connectivity

### ISSUE THREAD

**Issue by tricky1024** [friendly-bits/geoip-shell#10]
I have run the setup script with no issues on a Debian 12 Azure VM but run into the issue there is no internet connectivity, please can you advise?

**Comment by friendly-bits** [comment]
Hi, did you configure geoip-shell at least once?

It is possible that the server was temporarily unavailable - please try running `geoip-shell configure` and see if the issue is resolved.

If not then:

Please post the contents of this file: /etc/geoip-shell/geoip-shell.conf

And the output of these commands (run on your VM):
`ping 8.8.8.8`
`ping www.ipdeny.com`
`nslookup www.ipdeny.com 8.8.8.8`
`nslookup stat.ripe.net 8.8.8.8`

**Comment by tricky1024** [comment]
ok found the issue, needed to install dnsutils, many thanks for diag above.

**Comment by tricky1024** [comment]
further issues now, when i restart iptables it removed the geoblocking rules. this is a fusionpbx if it helps.

**Comment by friendly-bits** [comment]
What do you mean by "restart iptables"? Please write the exact commands you are issuing.

**Comment by tricky1024** [comment]
sudo iptables -vL -t mangle
Chain PREROUTING (policy ACCEPT 272K packets, 66M bytes)
 pkts bytes target     prot opt in     out     source               destination
 1106  630K GEOIP-SHELL  all  --  any    any     anywhere             anywhere             /* geoip-shell_enable */

Chain INPUT (policy ACCEPT 273K packets, 67M bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 274K packets, 69M bytes)
 pkts bytes target     prot opt in     out     source               destination
 249K   50M DSCP       udp  --  any    any     anywhere             anywhere             udp spts:16384:32768 DSCP set 0x2e
  605  417K DSCP       udp  --  any    any     anywhere             anywhere             udp spts:sip:5091 DSCP set 0x1a
 3205 1198K DSCP       tcp  --  any    any     anywhere             anywhere             tcp spts:sip:5091 DSCP set 0x1a

Chain POSTROUTING (policy ACCEPT 274K packets, 69M bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain GEOIP-SHELL (1 references)
 pkts bytes target     prot opt in     out     source               destination
  489  521K ACCEPT     all  --  lo     any     anywhere             anywhere             /* geoip-shell_aux-lo */
 9080 2234K ACCEPT     all  --  any    any     anywhere             anywhere             ctstate RELATED,ESTABLISHED /* geoip-shell_aux_rel-est */
    0     0 ACCEPT     all  --  any    any     anywhere             anywhere             match-set lan_ips_ipv4_geoip-shell src /* lan_ips_ipv4_geoip-shell_aux */
   75  6448 ACCEPT     all  --  any    any     anywhere             anywhere             match-set GB_ipv4_geoip-shell src /* GB_ipv4_geoip-shell */
    0     0 ACCEPT     all  --  any    any     anywhere             anywhere             match-set IE_ipv4_geoip-shell src /* IE_ipv4_geoip-shell */
    0     0 ACCEPT     all  --  any    any     anywhere             anywhere             match-set NL_ipv4_geoip-shell src /* NL_ipv4_geoip-shell */
    1   398 DROP       all  --  any    any     anywhere             anywhere             /* geoip-shell_whitelist_block */

then if i issue a: sudo service iptables restart

Chain PREROUTING (policy ACCEPT 1484 packets, 298K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 1484 packets, 298K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 1461 packets, 310K bytes)
 pkts bytes target     prot opt in     out     source               destination
 1368  274K DSCP       udp  --  any    any     anywhere             anywhere             udp spts:16384:32768 DSCP set 0x2e
    4  3052 DSCP       udp  --  any    any     anywhere             anywhere             udp spts:sip:5091 DSCP set 0x1a
   13  1803 DSCP       tcp  --  any    any     anywhere             anywhere             tcp spts:sip:5091 DSCP set 0x1a

Chain POSTROUTING (policy ACCEPT 1461 packets, 310K bytes)
 pkts bytes target     prot opt in     out     source               destination

**Comment by tricky1024** [comment]
Config in /etc/geoip-shell/geoip-shell.conf:

tcp_ports=skip
udp_ports=skip
geosource=ripe
lan_ips_ipv4=net:10.0.1.0/24
lan_ips_ipv6=net:fe80::/64
autodetect=
trusted_ipv4=
trusted_ipv6=
nft_perf=memory
ifaces=all
geomode=whitelist
datadir=/var/lib/geoip-shell
nobackup=false
no_persist=false
http=
user_ccode=GB
schedule=12 4 * * *
families=ipv4 ipv6
_fw_backend=ipt
max_attempts=30
reboot_sleep=30
bk_ext=bz2
iplists=GB_ipv4 GB_ipv6 IE_ipv4 IE_ipv6 NL_ipv4 NL_ipv6
noblock=false

**Comment by friendly-bits** [comment]
This works as expected. Restarting this service removes any existing iptables rules. Not only geoip-shell rules but all rules. Not sure why you still have some rules in the OUTPUT chain after that. Perhaps there is some system service which re-adds them automatically.
Generally in most cases you don't need to manually restart iptables, but if for some reason you do then you can restore geoip-shell rules with this command: `geoip-shell-run.sh restore`

**Comment by tricky1024** [comment]
perfect, thank you for the clarification.

**Comment by friendly-bits** [comment]
P.s. I will improve the code which handles the internet connectivity check to accommodate cases where nslookup is missing.
