### ISSUE TITLE
Enhancement: Local LAN add-to-auto

### ISSUE THREAD

**Issue by genekellyjr** [friendly-bits/geoip-shell#25]
I've run into trouble in two different ways with the auto feature that could be ameliorated with a way to append to auto. For reference, I use the allowlist mode which means that local IP groups that aren't detected are ditched.

**First case:**

I've had my docker stack down for a bit, so when geoip-shell did its check it didn't find the `172.17.0.0/24` range in use. When I brought up the stack, no container could access the internet - oops!

**Second case:**

I turned on the outbound blocking, thanks for adding that cool af feature, and I found out that the VPS I'm using has its DNS set to `169.254.169.254` which is a "link-local" address but was not detected.

In both cases, I'd love to have the auto pick up whatever it likes while having a way to define some "essential" ones so that they are always good-to-go, even if not spotted or in use when auto checks.

**Comment by friendly-bits** [comment]
Hi and thank you for reporting the issues.

> I've had my docker stack down for a bit, so when geoip-shell did its check it didn't find the `172.17.0.0/24` range in use. When I brought up the stack, no container could access the internet - oops!

This is indeed a scenario I haven't thought about. I'm not sure how to address it, though. Generally when no LAN subnets are detected in 'auto' mode, the apply script should halt the execution and then old rules should be restored. At least this is how it is supposed to work. I'll verify that this is indeed the case. Anyway, when **some** LAN subnets are detected, the 'auto' feature doesn't check if these are the same subnets as before or not, as it has no way to tell whether the network environment permanently changed or if it's temporarily down. So perhaps using the 'auto' feature, while convenient, simply has this drawback and I should advise the users to not rely on it alone but rather configure their current LAN subnets as 'trusted'. Maybe even add code to automate this during the initial setup.

Which addresses your suggested solution: to my understanding, what you are asking for is already implemented in the form of 'trusted ip's subnets'. Perhaps I should clarify in the docs that one can use this feature to specify any trusted ip addresses or subnets, including ones in their local network. Does this solve the 1st case for you?

> I turned on the outbound blocking, thanks for adding that cool af feature, and I found out that the VPS I'm using has its DNS set to `169.254.169.254` which is a "link-local" address but was not detected.

This is an oversight by me. Currently geoip-shell only creates rules allowing ipv6 link-local addresses in whitelist mode. I will definitely add code to also allow ipv4 link-local addresses.
