### ISSUE TITLE
Build a set for a state instead of country?

### ISSUE THREAD

**Issue by woolmonkey** [friendly-bits/geoip-shell#5]
Hello I was wondering is it possible to build a set for a single state instead of the whole country?

**Comment by friendly-bits** [comment]
Hi, technically it's possible, provided that you have the ip lists for given states. The sources geoip-shell uses don't have these lists. If you would like to recommend a source that does then I can take a look into integrating it.

**Comment by friendly-bits** [comment]
I'm closing this issue for now due to inactivity.
